{
	"version": 1585329033,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/enemysinhorizontal-sheet0.png",
		"images/enemysinvertical-sheet0.png",
		"images/enemyidle-sheet0.png",
		"images/particlesblack.png",
		"images/pièceor-sheet0.png",
		"images/particlespièceor.png",
		"images/pièceargent-sheet0.png",
		"images/piècebronze-sheet0.png",
		"images/particlespièceargent.png",
		"images/particlespiècebronze.png",
		"images/background-sheet0.png",
		"images/backgroundstart-sheet0.png",
		"images/backgroundcrédit-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/sprite-sheet0.png",
		"images/coins-sheet0.png",
		"media/powerup5.ogg",
		"media/laser9.ogg",
		"media/deep space.ogg",
		"media/space walk.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}